FROM nginx
COPY index.html /usr/share/nginx/html
COPY teampic.png /usr/share/nginx/html
COPY lauren.jpeg /usr/share/nginx/html
COPY lauren.html /usr/share/nginx/html
COPY bibek.html /usr/share/nginx/html
COPY Bibz.jpg /usr/share/nginx/html
COPY orla.html /usr/share/nginx/html
COPY orla.jpg /usr/share/nginx/html
EXPOSE 80
